# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: 下载geoip数据

on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 获取系统日期
        id: datetime
        run: echo "time=$(date +%Y%m%d%H%M%S)" > $GITHUB_OUTPUT
      - uses: actions/checkout@master
        id: git_checkout
      - name: 下载资源文件
        run: |
          ls
          cd .
          ls
          ./wget_ipinfo.sh ${{ github.token }}1
      - name: 发布版本
        run: |
          ls
          git add .
          git commit -m "版本发布${{ steps.datetime.outputs.time }}"
          git push origin
          git tag ${{ steps.datetime.outputs.time }}
          git push origin ${{ steps.datetime.outputs.time }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.datetime.outputs.time }}
          release_name: Release ${{ steps.datetime.outputs.time }}
          draft: false
          prerelease: false
      - name: 移除版本
        run: git push --delete origin ${{ steps.datetime.outputs.time }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: 发布文件
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./asn.mmdb
          asset_name: asn.mmdb
          asset_content_type: application/octet-stream
