# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: 下载更新发版

on: 
  workflow_dispatch:
  schedule:
    - cron: "30 3,11,19 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 下载文件
        run: |
          arr=( asn.mmdb asn.json.gz asn.csv.gz country.mmdb country.json.gz country.csv.gz country_asn.mmdb country_asn.json.gz country_asn.csv.gz )
          for v in ${arr[*]}; do wget https://ipinfo.io/data/free/${v}?token=${{ secrets.IPINFO_TOKEN }} -O ./${v}; done
      - name: 提交geoIP文件${{ matrix.name }}
        run: |
          git config --global user.email "preferhu@qq.com"
          git config --global user.name "cnartlu"
          git add .
          git commit -m "提交更新文件${{ matrix.name }}"
          git push
        env:
          GITHUB_TOKEN: ${{ github.token }}
  release:
    needs: [build]
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      tag_name: ${{ steps.create_tag.outputs.tag_name }}
    steps:
      - uses: actions/checkout@master
      - name: 获取tag名称
        id: create_tag
        run: echo "tag_name=V$(date +%Y%m%d%H)" > $GITHUB_OUTPUT
      - uses: actions/checkout@master
        id: git_checkout          
      - name: 发布版本
        run: |
          git tag ${{ steps.create_tag.outputs.tag_name }}
          git push origin ${{ steps.create_tag.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag_name }}
          release_name: Release ${{ steps.create_tag.outputs.tag_name }}
          draft: false
          prerelease: false

  upload:
    needs: [build, release]
    strategy:
      matrix:
        include:
          - name: asn.mmdb
          - name: asn.json.gz
          - name: asn.csv.gz
          - name: country.mmdb
          - name: country.json.gz
          - name: country.csv.gz
          - name: country_asn.mmdb
          - name: country_asn.json.gz
          - name: country_asn.csv.gz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 发布文件
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./${{ matrix.name }}
          asset_name: ${{ matrix.name }}
          asset_content_type: application/octet-stream
